site_name: Simple Networking
nav:
    - Home: index.md
    - 'Getting Started': 'GettingStarted.md'
theme:
    name: readthedocs    
markdown_extensions:
    - codehilite
repo_url: https://github.com/lalitadithya/SimpleNetworking
site_author: 'Lalit Adithya'